//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcYoutube.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analytic
    {
        public int Id { get; set; }
        public string VideoId { get; set; }
        public double WatchedTime { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
